server:
  port: 8090

spring:

  application:
    name: watermelon-user-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/watermelon-user?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:9000


logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

