server:
  port: 8090

spring:

  application:
    name: watermelon-tenant-user-server


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/watermelon?currentSchema=tenant-user&autoReconnect=true&stringtype=unspecified
    username: postgres
    password: 123456


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:9000


logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

